'use client';
import React, { useState, type FormEvent } from 'react';
import { beginLogin, verifyOtp } from '../../lib/api';
import { CatalogStep } from './CatalogStep';
import { SeatStep } from './SeatStep';
import type { Movie, Theatre } from './booking.types';
/** Runs the accessible mobile-number and fixed-OTP booking entry flow. */
export function BookingFlow(): JSX.Element {
  const [mobileNumber, setMobileNumber] = useState(''); const [otp, setOtp] = useState('');
  const [stage, setStage] = useState<'mobile' | 'otp' | 'catalog' | 'seat'>('mobile');
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [movies, setMovies] = useState<Movie[]>([]); const [theatres, setTheatres] = useState<Theatre[]>([]);
  async function submitMobile(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { await beginLogin(mobileNumber); setStage('otp'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not start login.'); } finally { setBusy(false); } }
  async function submitOtp(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const result = await verifyOtp(mobileNumber, otp); sessionStorage.setItem('sessionToken', result.token); const response = await fetch('/api/movies'); setMovies(await response.json() as Movie[]); setStage('catalog'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not verify OTP.'); } finally { setBusy(false); } }
  async function chooseMovie(movie: Movie) { const response = await fetch(`/api/theatres?movieId=${movie.id}`); setTheatres(await response.json() as Theatre[]); }
  return <section className="min-h-screen bg-cinema-50 px-5 py-14 text-stone-900"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 shadow-xl"><p className="mb-2 text-sm font-bold uppercase tracking-[.2em] text-cinema-700">REELBOOK / HYDERABAD</p><h1 className="font-display text-5xl font-bold">Your next film starts here.</h1><p className="mt-3 text-stone-600">Sign in with the demo OTP to discover today&apos;s shows.</p>{stage==='mobile'&&<form className="mt-8 space-y-4" onSubmit={submitMobile}><label className="block font-semibold" htmlFor="mobile">Mobile number</label><input id="mobile" aria-required="true" pattern="[0-9]{10}" value={mobileNumber} onChange={(event)=>setMobileNumber(event.target.value.replace(/\D/g,''))} className="w-full rounded-xl border border-stone-300 p-3" inputMode="numeric" required /><button disabled={busy} className="w-full rounded-xl bg-cinema-500 p-3 font-bold text-white disabled:opacity-60">{busy?'Sending…':'Continue'}</button></form>}{stage==='otp'&&<form className="mt-8 space-y-4" onSubmit={submitOtp}><label className="block font-semibold" htmlFor="otp">Enter OTP</label><input id="otp" aria-required="true" value={otp} onChange={(event)=>setOtp(event.target.value.replace(/\D/g,''))} className="w-full rounded-xl border border-stone-300 p-3" inputMode="numeric" maxLength={4} required /><p className="text-sm text-stone-500">Demo OTP: 1234</p><button disabled={busy} className="w-full rounded-xl bg-cinema-500 p-3 font-bold text-white disabled:opacity-60">{busy?'Verifying…':'Verify & browse movies'}</button></form>}{stage==='catalog'&&<CatalogStep movies={movies} theatres={theatres} onMovie={chooseMovie} onTheatre={()=>setStage('seat')}/>} {stage==='seat'&&<SeatStep onSelect={()=>setMessage('A1, A2, A3 selected for Rs. 450.')}/>} {message&&<p className="mt-4 text-cinema-700" role="alert">{message}</p>}</div></section>;
}
